nominal_vars : 
        ['team','hours','day','opponent','formation', 'venue','days_since_game'] #might need to remove formation if can't get access to it for upcoming games

train_vars_to_roll: 
        ['poss','touches','def pen','def 3rd', 'mid 3rd', 'att 3rd', 'att pen', 'live',
         'totdist','prgdist','ast','xag','xa','kp','1/3','ppa','crspa','prgp',
         'gls','sh','sot','sot%','g/sh','g/sot','dist','fk','pk','pkatt','xg','npxg',
         'npxg/sh','g-xg','np:g-xg','gf','ga',
         'y_true'
        ]

datasets:
        #["match_data_EPL_to_predict.csv"]
        ["match_data_BundesLiga.csv", "match_data_EPL.csv", "match_data_LaLiga.csv", "match_data_Ligue1.csv", "match_data_SerieA.csv"]

filters:
    "comp=='Premier League' or comp=='Bundesliga' or comp=='Serie A' or comp=='Ligue 1' or comp=='La Liga'"

n_days_lag: 3

n_days_rolling: 
        [5]
        #[5,10]

    

#some teams have different names in the Team and Opponent column
#for some reason I can't replace '-' with ' '... so have to brute force replace them :(
team_mapping:
    'Aston Villa': 'Aston-Villa'
    'Brighton': 'Brighton-and-Hove-Albion'
    'Cardiff City': 'Cardiff-City'
    'Cardiff': 'Cardiff-City'
    'Crystal Palace': 'Crystal-Palace'
    'Huddersfield': 'Huddersfield-Town'
    'Leeds United': 'Leeds-United'
    'Leeds': 'Leeds-United'
    'Leicester City': 'Leicester-City'
    'Leicester': 'Leicester-City'
    'Manchester City': 'Manchester-City'
    'Man City': 'Manchester-City'
    'Manchester Utd': 'Manchester-United'
    'Man United': 'Manchester-United'
    'Newcastle Utd': 'Newcastle-United'
    'Newcastle': 'Newcastle-United'
    'Norwich City': 'Norwich-City'
    'Norwich': 'Norwich-City'
    "Nott'ham Forest": 'Nottingham-Forest'
    "Nott'm Forest": 'Nottingham-Forest'
    'Sheffield Utd': 'Sheffield-United'
    'Sheffield United': 'Sheffield-United'
    'Stoke City': 'Stoke-City'
    'Stoke': 'Stoke-City'
    'Swansea City': 'Swansea-City'
    'Swansea': 'Swansea-City'
    'Tottenham': 'Tottenham-Hotspur'
    'West Brom': 'West-Bromwich-Albion'
    'West Ham': 'West-Ham-United'
    'Wolves': 'Wolverhampton-Wanderers'

    'Bayern Munich': 'Bayern-Munich'
    'Union Berlin': 'Union-Berlin'
    'RB Leipzig': 'RB-Leipzig'
    'Bayer Leverkusen': 'Bayer-Leverkusen'
    'Leverkusen': 'Bayer-Leverkusen'
    'Mainz 05': 'Mainz-05'
    'Mainz': 'Mainz-05'
    'Eint Frankfurt': 'Eintracht-Frankfurt'
    'Ein Frankfurt': 'Eintracht-Frankfurt'
    "M'Gladbach": 'Monchengladbach'
    "M'gladbach": 'Monchengladbach'
    'Köln': 'Koln'
    'FC Koln': 'Koln'
    'Werder Bremen': 'Werder-Bremen'
    'Schalke 04': 'Schalke-04'
    'Hertha BSC': 'Hertha-BSC'
    'Hertha': 'Hertha-BSC'
    'Greuther Fürth': 'Greuther-Furth'
    'Greuther Furth': 'Greuther-Furth'
    'Düsseldorf': 'Dusseldorf'
    'Fortuna Dusseldorf': 'Dusseldorf'
    'Paderborn 07': 'Paderborn-07'
    'Paderborn': 'Paderborn-07'
    'Hannover 96': 'Hannover-96'
    'Hannover': 'Hannover-96'
    'Hamburger SV': 'Hamburger-SV'
    'Hamburg': 'Hamburger-SV'
    'Nürnberg': 'Nurnberg'
    'Bielefeld': 'Arminia'

    'Rayo Vallecano': 'Rayo-Vallecano'
    'Espanol': 'Espanyol'
    'Vallecano': 'Rayo-Vallecano'
    'Real Sociedad': 'Real-Sociedad'
    'Sociedad': 'Real-Sociedad'
    'Cádiz': 'Cadiz'
    'Celta Vigo': 'Celta-Vigo'
    'Celta': 'Celta-Vigo'
    'Real Madrid': 'Real-Madrid'
    'Athletic Club': 'Athletic-Club'
    'Ath Bilbao': 'Athletic-Club'
    'Almería': 'Almeria'
    'Atlético Madrid': 'Atletico-Madrid'
    'Ath Madrid': 'Atletico-Madrid'
    'Betis': 'Real-Betis'
    'Alavés': 'Alaves'
    'Leganés': 'Leganes'
    'Las Palmas': 'Las-Palmas'
    'Málaga': 'Malaga'
    'La Coruña': 'Deportivo-La-Coruna'
    'La Coruna': 'Deportivo-La-Coruna'

    'Clermont Foot': 'Clermont-Foot'
    'Clermont': 'Clermont-Foot'
    'Paris S-G': 'Paris-Saint-Germain'
    'Paris SG': 'Paris-Saint-Germain'
    'Saint-Étienne': 'Saint-Etienne'
    'St Etienne': 'Saint-Etienne'
    'Nîmes': 'Nimes'

    'Hellas Verona': 'Hellas-Verona'
    'Verona': 'Hellas-Verona'
    'Spal': 'SPAL'
    'Inter': 'Internazionale'
    


